Repository Konkuk-KUIT/KUIT3_iOS, pull requests merged in 2024-05, with the labels that each got.

#25 [Week5-jisung] 5주차 미션을 제출합니다
  05_jisung/Week3/Setting/Setting/NameModifyView.swift
  05_jisung/Week4/Instagram/Instagram/SearchView.swift
  05_jisung/Week5/Calendar/Calendar.xcodeproj/project.pbxproj
  05_jisung/Week5/Calendar/Calendar.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  05_jisung/Week5/Calendar/Calendar.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/AccentColor.colorset/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/AppIcon.appiconset/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Birthday.imageset/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Birthday.imageset/Image.png
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Christmas.imageset/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Christmas.imageset/Image.png
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Concert.imageset/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Concert.imageset/Image.png
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Food.imageset/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Food.imageset/Image.png
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Playground.imageset/Contents.json
  05_jisung/Week5/Calendar/Calendar/Assets.xcassets/Playground.imageset/Image.png
  05_jisung/Week5/Calendar/Calendar/CalendarApp.swift
  05_jisung/Week5/Calendar/Calendar/ContentView.swift
  05_jisung/Week5/Calendar/Calendar/DateExtension.swift
  05_jisung/Week5/Calendar/Calendar/MonthView.swift
  05_jisung/Week5/Calendar/Calendar/OverlayView.swift
  05_jisung/Week5/Calendar/Calendar/Preview Content/Preview Assets.xcassets/Contents.json
  05_jisung/Week5/Calendar/Calendar/Story.swift
Labels: 지성, 5주차

#26 [Week5-ahyun] 5주차 미션을 제출합니다
  04_ahyun/Week05/InstaCalendar/InstaCalendar.xcodeproj/project.pbxproj
  04_ahyun/Week05/InstaCalendar/InstaCalendar.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  04_ahyun/Week05/InstaCalendar/InstaCalendar.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  04_ahyun/Week05/InstaCalendar/InstaCalendar.xcodeproj/xcuserdata/jung-ahhyun.xcuserdatad/xcschemes/xcschememanagement.plist
  04_ahyun/Week05/InstaCalendar/InstaCalendar/Assets.xcassets/AccentColor.colorset/Contents.json
  04_ahyun/Week05/InstaCalendar/InstaCalendar/Assets.xcassets/AppIcon.appiconset/Contents.json
  04_ahyun/Week05/InstaCalendar/InstaCalendar/Assets.xcassets/Contents.json
  04_ahyun/Week05/InstaCalendar/InstaCalendar/Assets.xcassets/image1.imageset/Contents.json
  04_ahyun/Week05/InstaCalendar/InstaCalendar/Assets.xcassets/image1.imageset/image3.jpg
  04_ahyun/Week05/InstaCalendar/InstaCalendar/ContentView.swift
  04_ahyun/Week05/InstaCalendar/InstaCalendar/DateExtension.swift
  04_ahyun/Week05/InstaCalendar/InstaCalendar/InstaCalendarApp.swift
  04_ahyun/Week05/InstaCalendar/InstaCalendar/Preview Content/Preview Assets.xcassets/Contents.json
Labels: 아현, 5주차

#27 [Week5-ParkSeongGeun] 5주차 미션 제출합니다.
  03_seonggeun/Week5/CalendarPractice/CalendarPractice.xcodeproj/project.pbxproj
  03_seonggeun/Week5/CalendarPractice/CalendarPractice.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  03_seonggeun/Week5/CalendarPractice/CalendarPractice.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  03_seonggeun/Week5/CalendarPractice/CalendarPractice/Assets.xcassets/AccentColor.colorset/Contents.json
  03_seonggeun/Week5/CalendarPractice/CalendarPractice/Assets.xcassets/AppIcon.appiconset/Contents.json
  03_seonggeun/Week5/CalendarPractice/CalendarPractice/Assets.xcassets/Contents.json
  03_seonggeun/Week5/CalendarPractice/CalendarPractice/CalendarPracticeApp.swift
  03_seonggeun/Week5/CalendarPractice/CalendarPractice/ContentView.swift
  03_seonggeun/Week5/CalendarPractice/CalendarPractice/Preview Content/Preview Assets.xcassets/Contents.json
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar.xcodeproj/project.pbxproj
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Assets.xcassets/AccentColor.colorset/Contents.json
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Assets.xcassets/AppIcon.appiconset/Contents.json
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Assets.xcassets/BlackMan.imageset/BlackMan.png
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Assets.xcassets/BlackMan.imageset/Contents.json
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Assets.xcassets/Contents.json
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Assets.xcassets/GreenMan.imageset/Contents.json
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Assets.xcassets/GreenMan.imageset/GreenMan.png
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/ContentView.swift
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/InstagramCalendarApp.swift
  03_seonggeun/Week5/InstagramCalendar/InstagramCalendar/Preview Content/Preview Assets.xcassets/Contents.json
Labels: 성근, 5주차

#30 [Week6-jisung] 애니메이션 미션을 제출합니다
  05_jisung/Week5/Calendar/Calendar/ContentView.swift
  05_jisung/Week5/Calendar/Calendar/OverlayView.swift
  05_jisung/Week6/Animation/Animation.xcodeproj/project.pbxproj
  05_jisung/Week6/Animation/Animation.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  05_jisung/Week6/Animation/Animation.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  05_jisung/Week6/Animation/Animation/AnimationApp.swift
  05_jisung/Week6/Animation/Animation/Assets.xcassets/AccentColor.colorset/Contents.json
  05_jisung/Week6/Animation/Animation/Assets.xcassets/AppIcon.appiconset/Contents.json
  05_jisung/Week6/Animation/Animation/Assets.xcassets/Contents.json
  05_jisung/Week6/Animation/Animation/ContentView.swift
  05_jisung/Week6/Animation/Animation/DragAnimation.swift
  05_jisung/Week6/Animation/Animation/FocusAnimation.swift
  05_jisung/Week6/Animation/Animation/Preview Content/Preview Assets.xcassets/Contents.json
  05_jisung/Week6/Animation/Animation/SubstringHighlighter.swift
Labels: 지성, 6주차

#31 [Week06-ahyun] 애니메이션 미션 제출합니다.
  04_ahyun/Week06/Animation/Animation.xcodeproj/project.pbxproj
  04_ahyun/Week06/Animation/Animation.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  04_ahyun/Week06/Animation/Animation.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  04_ahyun/Week06/Animation/Animation/AnimatablePair.swift
  04_ahyun/Week06/Animation/Animation/AnimationApp.swift
  04_ahyun/Week06/Animation/Animation/Assets.xcassets/AccentColor.colorset/Contents.json
  04_ahyun/Week06/Animation/Animation/Assets.xcassets/AppIcon.appiconset/Contents.json
  04_ahyun/Week06/Animation/Animation/Assets.xcassets/Contents.json
  04_ahyun/Week06/Animation/Animation/Cat.swift
  04_ahyun/Week06/Animation/Animation/ContentView.swift
  04_ahyun/Week06/Animation/Animation/Line.swift
  04_ahyun/Week06/Animation/Animation/Preview Content/Preview Assets.xcassets/Contents.json
Labels: 아현, 6주차

#33 [Week07-ahyun] DispatchQueue 미션 제출합니다
  04_ahyun/Week07/DispatchQueue/DispatchQueue.xcodeproj/project.pbxproj
  04_ahyun/Week07/DispatchQueue/DispatchQueue.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  04_ahyun/Week07/DispatchQueue/DispatchQueueEx.playground/Contents.swift
  04_ahyun/Week07/DispatchQueue/DispatchQueueEx.playground/contents.xcplayground
Labels: 아현, 7주차

#34 [Week7-박성근] 7주차 미션을 제출합니다
  03_seonggeun/Week7/MyPlayground.playground/Contents.swift
  03_seonggeun/Week7/MyPlayground.playground/contents.xcplayground
  03_seonggeun/Week7/MyPlayground.playground/playground.xcworkspace/contents.xcworkspacedata
Labels: 성근, 7주차

#35 [Week7-jisung] Dispatch미션을 제출합니다
  05_jisung/Week6/Animation/Animation/DragAnimation.swift
  05_jisung/Week7/DispatchProject/DispatchProject.xcodeproj/project.pbxproj
  05_jisung/Week7/DispatchProject/DispatchProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  05_jisung/Week7/DispatchProject/DispatchProject.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  05_jisung/Week7/DispatchProject/DispatchProject/Assets.xcassets/AccentColor.colorset/Contents.json
  05_jisung/Week7/DispatchProject/DispatchProject/Assets.xcassets/AppIcon.appiconset/Contents.json
  05_jisung/Week7/DispatchProject/DispatchProject/Assets.xcassets/Contents.json
  05_jisung/Week7/DispatchProject/DispatchProject/ContentView.swift
  05_jisung/Week7/DispatchProject/DispatchProject/DispatchProjectApp.swift
  05_jisung/Week7/DispatchProject/DispatchProject/Preview Content/Preview Assets.xcassets/Contents.json
Labels: 지성, 7주차

#37 [Week8-jisung] HTTP method 미션을 제출합니다
  05_jisung/Week8/NetworkRequest/NetworkRequest.xcodeproj/project.pbxproj
  05_jisung/Week8/NetworkRequest/NetworkRequest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  05_jisung/Week8/NetworkRequest/NetworkRequest.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  05_jisung/Week8/NetworkRequest/NetworkRequest/AlamofirePractice.swift
  05_jisung/Week8/NetworkRequest/NetworkRequest/Assets.xcassets/AccentColor.colorset/Contents.json
  05_jisung/Week8/NetworkRequest/NetworkRequest/Assets.xcassets/AppIcon.appiconset/Contents.json
  05_jisung/Week8/NetworkRequest/NetworkRequest/Assets.xcassets/Contents.json
  05_jisung/Week8/NetworkRequest/NetworkRequest/ContentView.swift
  05_jisung/Week8/NetworkRequest/NetworkRequest/NetworkRequestApp.swift
  05_jisung/Week8/NetworkRequest/NetworkRequest/Preview Content/Preview Assets.xcassets/Contents.json
Labels: 지성

#39 [Week08-ahyun] 8주차 미션을 제출합니다.
  04_ahyun/Week08/Week8App/Week8App.xcodeproj/project.pbxproj
  04_ahyun/Week08/Week8App/Week8App/Assets.xcassets/AccentColor.colorset/Contents.json
  04_ahyun/Week08/Week8App/Week8App/Assets.xcassets/AppIcon.appiconset/Contents.json
  04_ahyun/Week08/Week8App/Week8App/Assets.xcassets/Contents.json
  04_ahyun/Week08/Week8App/Week8App/ContentView.swift
  04_ahyun/Week08/Week8App/Week8App/Preview Content/Preview Assets.xcassets/Contents.json
  04_ahyun/Week08/Week8App/Week8App/UserAPI.swift
  04_ahyun/Week08/Week8App/Week8App/Week8App.entitlements
  04_ahyun/Week08/Week8App/Week8App/Week8App.swift
Labels: 아현
