Repository Konkuk-KUIT/KUIT3_iOS, pull requests merged in 2024-03, with the labels that each got.

#10 [Week2] 미션 코드
  00_lecture/Week2/Weather/Weather.xcodeproj/project.pbxproj
  00_lecture/Week2/Weather/Weather.xcodeproj/project.xcworkspace/xcuserdata/ga-eun.xcuserdatad/UserInterfaceState.xcuserstate
  00_lecture/Week2/Weather/Weather/ContentView.swift
Labels: 2주차

#6 [Week2-ParkSeongGeun] 2주차 미션 제출입니다
  03_seonggeun/Week2/Weather.xcodeproj/project.pbxproj
  03_seonggeun/Week2/Weather.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  03_seonggeun/Week2/Weather.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  03_seonggeun/Week2/Weather/Assets.xcassets/AccentColor.colorset/Contents.json
  03_seonggeun/Week2/Weather/Assets.xcassets/AppIcon.appiconset/Contents.json
  03_seonggeun/Week2/Weather/Assets.xcassets/Contents.json
  03_seonggeun/Week2/Weather/Assets.xcassets/background.imageset/Contents.json
  03_seonggeun/Week2/Weather/Assets.xcassets/background.imageset/background.jpg
  03_seonggeun/Week2/Weather/ContentView.swift
  03_seonggeun/Week2/Weather/Preview Content/Preview Assets.xcassets/Contents.json
  03_seonggeun/Week2/Weather/WeatherApp.swift
Labels: 2주차, 성근

#7 [Week02- ahyun] 2주차 미션 제출합니다.
  04_ahyun/.gitignore
  04_ahyun/Week01/FirstApp/FirstApp.xcodeproj/project.xcworkspace/xcuserdata/jung-ahhyun.xcuserdatad/UserInterfaceState.xcuserstate
  04_ahyun/Week01/FirstApp/FirstApp.xcodeproj/xcuserdata/jung-ahhyun.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  04_ahyun/Week01/FirstApp/FirstApp/Assets.xcassets/background.imageset/Contents.json
  04_ahyun/Week01/FirstApp/FirstApp/Assets.xcassets/background.imageset/background.JPG
  04_ahyun/Week01/FirstApp/FirstApp/ContentView.swift
  04_ahyun/Week02/Weather/Weather.xcodeproj/project.pbxproj
  04_ahyun/Week02/Weather/Weather.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  04_ahyun/Week02/Weather/Weather.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  04_ahyun/Week02/Weather/Weather.xcodeproj/project.xcworkspace/xcuserdata/jung-ahhyun.xcuserdatad/UserInterfaceState.xcuserstate
  04_ahyun/Week02/Weather/Weather.xcodeproj/xcuserdata/jung-ahhyun.xcuserdatad/xcschemes/xcschememanagement.plist
  04_ahyun/Week02/Weather/Weather/Assets.xcassets/AccentColor.colorset/Contents.json
  04_ahyun/Week02/Weather/Weather/Assets.xcassets/AppIcon.appiconset/Contents.json
  04_ahyun/Week02/Weather/Weather/Assets.xcassets/Contents.json
  04_ahyun/Week02/Weather/Weather/Assets.xcassets/background.imageset/Contents.json
  04_ahyun/Week02/Weather/Weather/Assets.xcassets/background.imageset/background.jpg
  04_ahyun/Week02/Weather/Weather/Assets.xcassets/moon.imageset/Contents.json
  04_ahyun/Week02/Weather/Weather/Assets.xcassets/moon.imageset/moon.png
  04_ahyun/Week02/Weather/Weather/ContentView.swift
  04_ahyun/Week02/Weather/Weather/Preview Content/Preview Assets.xcassets/Contents.json
  04_ahyun/Week02/Weather/Weather/WeatherApp.swift
Labels: 2주차, 아현

#8 [Week2-jisung] 2주차 미션을 제출합니다.
  05_jisung/Week2/Weather/Weather.xcodeproj/project.pbxproj
  05_jisung/Week2/Weather/Weather.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  05_jisung/Week2/Weather/Weather.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  05_jisung/Week2/Weather/Weather/Assets.xcassets/AccentColor.colorset/Contents.json
  05_jisung/Week2/Weather/Weather/Assets.xcassets/AppIcon.appiconset/Contents.json
  05_jisung/Week2/Weather/Weather/Assets.xcassets/Contents.json
  05_jisung/Week2/Weather/Weather/Assets.xcassets/moon.imageset/Contents.json
  05_jisung/Week2/Weather/Weather/Assets.xcassets/moon.imageset/Image.png
  05_jisung/Week2/Weather/Weather/Assets.xcassets/sunny.imageset/Contents.json
  05_jisung/Week2/Weather/Weather/Assets.xcassets/sunny.imageset/IMG_9033 2.jpg
  05_jisung/Week2/Weather/Weather/ContentView.swift
  05_jisung/Week2/Weather/Weather/MoonPhaseView.swift
  05_jisung/Week2/Weather/Weather/Preview Content/Preview Assets.xcassets/Contents.json
  05_jisung/Week2/Weather/Weather/TemperatureBarView.swift
  05_jisung/Week2/Weather/Weather/WeatherApp.swift
  05_jisung/Week2/Weather/Weather/WeatherForecastView.swift
Labels: 2주차, 지성

#9 [Week2-이현희] Stack 활용 미션 제출합니다.
  06_hyunhee/week01/FirstApp/FirstApp.xcodeproj/project.xcworkspace/xcuserdata/leehyunhee.xcuserdatad/UserInterfaceState.xcuserstate
  06_hyunhee/week02/SecondApp/SecondApp.xcodeproj/project.pbxproj
  06_hyunhee/week02/SecondApp/SecondApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  06_hyunhee/week02/SecondApp/SecondApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  06_hyunhee/week02/SecondApp/SecondApp.xcodeproj/xcshareddata/xcschemes/SecondApp.xcscheme
  06_hyunhee/week02/SecondApp/SecondApp/Assets.xcassets/AccentColor.colorset/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/Assets.xcassets/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/Assets.xcassets/background.imageset/20230119503755.jpg
  06_hyunhee/week02/SecondApp/SecondApp/Assets.xcassets/background.imageset/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/Colors.xcassets/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/Colors.xcassets/myBlue.colorset/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/Colors.xcassets/myGreen.colorset/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/ContentView.swift
  06_hyunhee/week02/SecondApp/SecondApp/DayWeatherData.swift
  06_hyunhee/week02/SecondApp/SecondApp/DayWeatherView.swift
  06_hyunhee/week02/SecondApp/SecondApp/Preview Content/Preview Assets.xcassets/Contents.json
  06_hyunhee/week02/SecondApp/SecondApp/SecondAppApp.swift
  06_hyunhee/week02/SecondApp/SecondAppTests/SecondAppTests.swift
  06_hyunhee/week02/SecondApp/SecondAppUITests/SecondAppUITests.swift
  06_hyunhee/week02/SecondApp/SecondAppUITests/SecondAppUITestsLaunchTests.swift
Labels: 2주차, 현희
