Repository Konkuk-KUIT/KUIT3_iOS, pull requests merged in 2024-04, with the labels that each got.

#12 [Week3-Park seong geun] 3주차 실습 과제 제출입니다.
  03_seonggeun/Week3/Setting/Setting.xcodeproj/project.pbxproj
  03_seonggeun/Week3/Setting/Setting.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  03_seonggeun/Week3/Setting/Setting.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  03_seonggeun/Week3/Setting/Setting/Assets.xcassets/AccentColor.colorset/Contents.json
  03_seonggeun/Week3/Setting/Setting/Assets.xcassets/AppIcon.appiconset/Contents.json
  03_seonggeun/Week3/Setting/Setting/Assets.xcassets/Contents.json
  03_seonggeun/Week3/Setting/Setting/Assets.xcassets/profile.imageset/Contents.json
  03_seonggeun/Week3/Setting/Setting/Assets.xcassets/profile.imageset/KakaoTalk_Photo_2024-04-01-15-59-02.jpeg
  03_seonggeun/Week3/Setting/Setting/ContentView.swift
  03_seonggeun/Week3/Setting/Setting/Contents.swift
  03_seonggeun/Week3/Setting/Setting/Preview Content/Preview Assets.xcassets/Contents.json
  03_seonggeun/Week3/Setting/Setting/ProfileSetting.swift
  03_seonggeun/Week3/Setting/Setting/SettingApp.swift
  03_seonggeun/Week3/Setting/Setting/SettingInfoView.swift
  03_seonggeun/Week3/Setting/Setting/UserInfoView.swift
Labels: 성근, 3주차

#13 [Week03-ahyun] 3주차 미션 제출합니다.
  04_ahyun/Week03/Setting/Setting.xcodeproj/project.pbxproj
  04_ahyun/Week03/Setting/Setting.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  04_ahyun/Week03/Setting/Setting.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  04_ahyun/Week03/Setting/Setting.xcodeproj/project.xcworkspace/xcuserdata/jung-ahhyun.xcuserdatad/UserInterfaceState.xcuserstate
  04_ahyun/Week03/Setting/Setting.xcodeproj/xcuserdata/jung-ahhyun.xcuserdatad/xcschemes/xcschememanagement.plist
  04_ahyun/Week03/Setting/Setting/Assets.xcassets/AccentColor.colorset/Contents.json
  04_ahyun/Week03/Setting/Setting/Assets.xcassets/AppIcon.appiconset/Contents.json
  04_ahyun/Week03/Setting/Setting/Assets.xcassets/Contents.json
  04_ahyun/Week03/Setting/Setting/Assets.xcassets/ahyun.imageset/Contents.json
  04_ahyun/Week03/Setting/Setting/Assets.xcassets/ahyun.imageset/ahyun.jpg
  04_ahyun/Week03/Setting/Setting/ContentView.swift
  04_ahyun/Week03/Setting/Setting/Preview Content/Preview Assets.xcassets/Contents.json
  04_ahyun/Week03/Setting/Setting/ProfileView.swift
  04_ahyun/Week03/Setting/Setting/SettingApp.swift
  04_ahyun/Week03/Setting/Setting/UserInfoView.swift
Labels: 아현, 3주차

#16 [Week3-hyunhee] 설정 앱 만들기 미션을 제출합니다.
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp.xcodeproj/project.pbxproj
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/AppleIDView.swift
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/Assets.xcassets/AccentColor.colorset/Contents.json
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/Assets.xcassets/Contents.json
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/ContentView.swift
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/Practice2SettingAppApp.swift
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/Preview Content/Preview Assets.xcassets/Contents.json
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingApp/ProfileView.swift
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingAppTests/Practice2SettingAppTests.swift
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingAppUITests/Practice2SettingAppUITests.swift
  06_hyunhee/week03/SettingApp/Practice2SettingApp/Practice2SettingAppUITests/Practice2SettingAppUITestsLaunchTests.swift
  06_hyunhee/week03/ThirdApp/ThirdApp.xcodeproj/project.pbxproj
  06_hyunhee/week03/ThirdApp/ThirdApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  06_hyunhee/week03/ThirdApp/ThirdApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  06_hyunhee/week03/ThirdApp/ThirdApp/Assets.xcassets/AccentColor.colorset/Contents.json
  06_hyunhee/week03/ThirdApp/ThirdApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  06_hyunhee/week03/ThirdApp/ThirdApp/Assets.xcassets/Contents.json
  06_hyunhee/week03/ThirdApp/ThirdApp/ContentView.swift
  06_hyunhee/week03/ThirdApp/ThirdApp/NextView.swift
  06_hyunhee/week03/ThirdApp/ThirdApp/Preview Content/Preview Assets.xcassets/Contents.json
  06_hyunhee/week03/ThirdApp/ThirdApp/ThirdAppApp.swift
  06_hyunhee/week03/ThirdApp/ThirdAppTests/ThirdAppTests.swift
  06_hyunhee/week03/ThirdApp/ThirdAppUITests/ThirdAppUITests.swift
  06_hyunhee/week03/ThirdApp/ThirdAppUITests/ThirdAppUITestsLaunchTests.swift
Labels: 현희, 3주차

#15 [Week3] 미션 코드 예시
  00_lecture/Week3/Setting/Setting.xcodeproj/project.pbxproj
  00_lecture/Week3/Setting/Setting/Assets.xcassets/user.imageset/Contents.json
  00_lecture/Week3/Setting/Setting/Assets.xcassets/user.imageset/TalkMedia_i_6b001de52c58.png.png
  00_lecture/Week3/Setting/Setting/ContentView.swift
  00_lecture/Week3/Setting/Setting/SettingInfoView.swift
  00_lecture/Week3/Setting/Setting/UserInfoView.swift
  00_lecture/Week3/Setting/Setting/UserView.swift
Labels: 3주차

#19 [Week3-이안진] 설정앱 그리기 미션을 제출합니다.
  01_anjin/Week03/SettingApp/SettingApp.xcodeproj/project.pbxproj
  01_anjin/Week03/SettingApp/SettingApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  01_anjin/Week03/SettingApp/SettingApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  01_anjin/Week03/SettingApp/SettingApp/Assets.xcassets/AccentColor.colorset/Contents.json
  01_anjin/Week03/SettingApp/SettingApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  01_anjin/Week03/SettingApp/SettingApp/Assets.xcassets/Contents.json
  01_anjin/Week03/SettingApp/SettingApp/Assets.xcassets/anjin.imageset/Contents.json
  01_anjin/Week03/SettingApp/SettingApp/Assets.xcassets/anjin.imageset/anjin.png
  01_anjin/Week03/SettingApp/SettingApp/ContentView.swift
  01_anjin/Week03/SettingApp/SettingApp/Preview Content/Preview Assets.xcassets/Contents.json
  01_anjin/Week03/SettingApp/SettingApp/ProfileView.swift
  01_anjin/Week03/SettingApp/SettingApp/SettingAppApp.swift
  01_anjin/Week03/SettingApp/SettingApp/SettingRow.swift
  01_anjin/Week03/SettingApp/SettingApp/User.swift
Labels: 3주차

#20 [Week4-ParkSeongGeun] 인스타 userinfoview, searchview 과제 제출입니다.
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding.xcodeproj/project.pbxproj
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/AccentColor.colorset/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/AppIcon.appiconset/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/Ellipse.imageset/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/Ellipse.imageset/Ellipse 81.png
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/Menu.imageset/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/Menu.imageset/Menu.png
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/PlusBlue.imageset/Component 2.png
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/PlusBlue.imageset/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/Threads.imageset/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Assets.xcassets/Threads.imageset/Threads.png
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/ContentView.swift
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/InstagramCloneCodingApp.swift
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/ModalView.swift
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/Preview Content/Preview Assets.xcassets/Contents.json
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/SearchView.swift
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/TabBar.swift
  03_seonggeun/Week4/InstagramCloneCoding/InstagramCloneCoding/UserView.swift
Labels: 성근, 4주차

#22 [Week5-jisung] 4주차 미션을 제출합니다
  05_jisung/Week4/Instagram/Instagram.xcodeproj/project.pbxproj
  05_jisung/Week4/Instagram/Instagram.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  05_jisung/Week4/Instagram/Instagram.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  05_jisung/Week4/Instagram/Instagram/10secTimer.mp4
  05_jisung/Week4/Instagram/Instagram/AddPostsView.swift
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/AccentColor.colorset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/AppIcon.appiconset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Component2.imageset/Component 2.svg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Component2.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Create.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Create.imageset/Create.svg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Grid.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Grid.imageset/Image.png
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta1.imageset/53598863344_57fb7caa79_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta1.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta10.imageset/53598386861_1bda3a99cd_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta10.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta2.imageset/53608713677_da808949d2_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta2.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta3.imageset/53618518957_c2c704a4fe_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta3.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta4.imageset/53627224191_9673e554c4_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta4.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta5.imageset/53630422413_c2093d4274_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta5.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta6.imageset/53634084067_5d0451e6ed_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta6.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta7.imageset/53634399766_b96fd9145b_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta7.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta8.imageset/53635135811_d9616421a6_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta8.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta9.imageset/53636304183_d9e5581c9a_w.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Insta9.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Menu.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Menu.imageset/Menu.svg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Profile.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Profile.imageset/IMG_9396.jpg
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Reels.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Reels.imageset/Image.png
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/StoryHilights.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/StoryHilights.imageset/Image.png
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Threads.imageset/Contents.json
  05_jisung/Week4/Instagram/Instagram/Assets.xcassets/Threads.imageset/Threads.svg
  05_jisung/Week4/Instagram/Instagram/ContentView.swift
  05_jisung/Week4/Instagram/Instagram/Grid1View.swift
  05_jisung/Week4/Instagram/Instagram/Grid2View.swift
  05_jisung/Week4/Instagram/Instagram/InstagramApp.swift
  05_jisung/Week4/Instagram/Instagram/Preview Content/Preview Assets.xcassets/Contents.json
  05_jisung/Week4/Instagram/Instagram/SearchView.swift
  05_jisung/Week4/Instagram/Instagram/TabBarView.swift
  05_jisung/Week4/Instagram/Instagram/UserView.swift
Labels: 지성, 4주차

#23 [Week4-hyunhee] instagram 미션 제출합니다
  06_hyunhee/week04/InstagramApp/InstagramApp.xcodeproj/project.pbxproj
  06_hyunhee/week04/InstagramApp/InstagramApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  06_hyunhee/week04/InstagramApp/InstagramApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  06_hyunhee/week04/InstagramApp/InstagramApp/Assets.xcassets/AccentColor.colorset/Contents.json
  06_hyunhee/week04/InstagramApp/InstagramApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  06_hyunhee/week04/InstagramApp/InstagramApp/Assets.xcassets/Contents.json
  06_hyunhee/week04/InstagramApp/InstagramApp/Assets.xcassets/sampleImage.imageset/Contents.json
  06_hyunhee/week04/InstagramApp/InstagramApp/Assets.xcassets/sampleImage.imageset/images.jpeg
  06_hyunhee/week04/InstagramApp/InstagramApp/ContentView.swift
  06_hyunhee/week04/InstagramApp/InstagramApp/InstagramAppApp.swift
  06_hyunhee/week04/InstagramApp/InstagramApp/Preview Content/Preview Assets.xcassets/Contents.json
  06_hyunhee/week04/InstagramApp/InstagramApp/SearchView.swift
  06_hyunhee/week04/InstagramApp/InstagramApp/TabBar.swift
  06_hyunhee/week04/InstagramApp/InstagramApp/UserView.swift
  06_hyunhee/week04/InstagramApp/InstagramAppTests/InstagramAppTests.swift
  06_hyunhee/week04/InstagramApp/InstagramAppUITests/InstagramAppUITests.swift
  06_hyunhee/week04/InstagramApp/InstagramAppUITests/InstagramAppUITestsLaunchTests.swift
Labels: 현희, 4주차
